<?php

return [
    'algorithm_version' => '2.0',
    'top_k' => 5,
    'scale' => ['min' => 1.0, 'max' => 5.0],
    'weights' => [
        'energy' => 1.0,
        'trainability' => 1.0,
        'independence' => 1.0,
        'temperament' => 1.0,
        'physical_size' => 1.0,
        'medical_needs' => 1.0,
    ],
    'min_observers' => 3,
    'min_answered_ratio' => 0.80,
    'independence' => ['reverse_attachment' => true],
    'filters' => [
        'reactive_threshold' => 4.0,
        'low_financial_level' => 2.0,
        'healthy_max_medical' => 2.0,
        'high_energy_threshold' => 4.0,
    ],
    'spatial_penalty' => 1.0,
    'housing' => [
        'Apartment / Condo' => 'apartment',
        'Townhouse' => 'house_no_yard',
        'Single Family Home (No Yard)' => 'house_no_yard',
        'Single Family Home (Fenced Yard)' => 'house_with_yard',
    ],
    'size_levels' => [
        'Extra Small' => 1.0, 'Small' => 2.0, 'Medium' => 3.0,
        'Large' => 4.0, 'Extra Large' => 5.0,
    ],
    'financial_levels' => [
        'Below ₱15,000' => 1, '₱15,000 - ₱30,000' => 2,
        '₱30,000 - ₱50,000' => 3, '₱50,000 - ₱80,000' => 4,
        'Above ₱80,000' => 5,
    ],
    'items' => [
        'dog' => [
            'energy' => [
                'E1' => 'Hyperactive, restless, has trouble settling down',
                'E2' => 'Playful, puppyish, boisterous',
                'E3' => 'Active, energetic, always on the go',
            ],
            'trainability' => [
                'T1' => 'When off the leash, returns immediately when called',
                'T2' => 'Obeys the sit command immediately',
                'T3' => 'Obeys the stay command immediately',
                'T4' => 'Seems to attend/listen closely to everything you say or do',
                'T5' => 'Slow to respond to punishment/correction or thick-skinned',
                'T6' => 'Slow to learn new tricks or tasks',
                'T7' => 'Easily distracted by interesting sights, sounds, or smells',
                'T8' => 'Will fetch or attempt to fetch sticks, balls, or objects',
            ],
            'attachment' => [
                'I1' => 'Displays a strong attachment for one particular household member',
                'I2' => 'Follows household members from room to room',
                'I3' => 'Sits close to, or in contact with, you when you are sitting down',
                'I4' => 'Nudges, nuzzles or paws you for attention when you are sitting down',
                'I5' => 'Becomes agitated when you show affection for another person',
                'I6' => 'Becomes agitated when you show affection for another animal',
            ],
            'stranger_fear' => [
                'SF1' => 'Fearful or cautious of unfamiliar people who visit the home',
                'SF2' => 'Fearful or cautious of strangers encountered in public spaces',
                'SF3' => 'Freezes, cowers, or trembles when confronted by strangers',
                'SF4' => 'Tucks tail or cringes in the presence of strangers',
                'SF5' => 'Hides behind the owner or retreats from unfamiliar people',
            ],
            'non_social_fear' => [
                'NF1' => 'Fearful or startled by sudden or loud noises',
                'NF2' => 'Fearful of traffic',
                'NF3' => 'Fearful of unfamiliar or strange-looking objects',
                'NF4' => 'Fearful of unfamiliar situations or new environments',
                'NF5' => 'Fearful of fast-moving objects',
                'NF6' => 'Fearful of walking on slippery or unfamiliar surfaces',
            ],
        ],
        'cat' => [
            'energy' => [
                'CE1' => 'Actively seeks play with toys',
                'CE2' => 'Actively seeks play with people',
                'CE3' => 'Runs, jumps, or climbs energetically',
                'CE4' => 'Engages in predatory play',
                'CE5' => 'Appears restless or unable to settle for extended periods',
            ],
            'trainability' => [
                'CT1' => 'Responds to its own name when called',
                'CT2' => 'Comes when called by name or a familiar sound',
                'CT3' => 'Follows basic cues or commands',
                'CT4' => 'Appears to learn new behaviors or routines quickly',
            ],
            'sociability' => [
                'CS1' => 'Approaches familiar people voluntarily',
                'CS2' => 'Seeks physical contact.',
                'CS3' => 'Remains in close proximity to the owner during daily activities',
            ],
            'attention_seeking' => [
                'CA1' => 'Vocalizes to attract the owner’s attention',
                'CA2' => 'Solicits petting or grooming from the owner',
                'CA3' => 'Follows the owner around the home throughout the day',
            ],
            'temperament' => [
                'TEM1' => 'Hisses, growls, or spits at unfamiliar people',
                'TEM2' => 'Swipes or scratches at unfamiliar people without apparent provocation',
                'TEM3' => 'Hides or runs away when unfamiliar people visit the home',
                'TEM4' => 'Shows fear when exposed to unfamiliar objects',
                'TEM5' => 'Startles easily at sudden sounds or unexpected stimuli',
                'TEM6' => 'Avoids new environments',
            ],
        ],
    ],
    'behavior_reverse' => ['dog.trainability.T5', 'dog.trainability.T6', 'dog.trainability.T7'],
    // Verify item keys and reverse-keying against the official BFI-2 scoring key before production.
    'bfi' => [
        'mapping_confirmed' => true,
        'dimensions' => [
            'extraversion' => ['EX1', 'EX2', 'EX3', 'EX4', 'EX5', 'EX6'],
            'conscientiousness' => ['C1', 'C2', 'C3', 'C4', 'C5', 'C6'],
            'neuroticism' => ['N1', 'N2', 'N3', 'N4'],
            'openness' => ['O1', 'O2', 'O3', 'O4'],
        ],
        'reverse' => ['EX2', 'EX3', 'EX6', 'C1', 'C4', 'C5', 'N1', 'N4', 'O2', 'O4'],
        'provisional_items' => ['O4'],
        'prompts' => [
            'EX1' => 'Is full of energy',
            'EX2' => 'Is less active than other people',
            'EX3' => 'Tends to be quiet',
            'EX4' => 'Is outgoing, sociable',
            'EX5' => 'Is dominant, acts as a leader',
            'EX6' => 'Prefers to have others take charge',
            'C1' => 'Has difficulty getting started on tasks',
            'C2' => 'Is persistent, works until the task is finished',
            'C3' => 'Is reliable, can always be counted on',
            'C4' => 'Can be somewhat careless',
            'C5' => 'Tends to be disorganized',
            'C6' => 'Keeps things neat and tidy',
            'N1' => 'Is emotionally stable, not easily upset',
            'N2' => 'Is temperamental, gets emotional easily',
            'N3' => 'Worries a lot',
            'N4' => 'Is relaxed, handles stress well',
            'O1' => 'Is original, comes up with new ideas',
            'O2' => 'Has few artistic interests',
            'O3' => 'Is fascinated by art, music, or literature',
            'O4' => 'Has few artistic interests', // Provisional duplicate from Table 12; do not invent wording.
        ],
    ],
];
